# Generated by Django 6.1 on 2026-08-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='record_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
