# Generated by Django 6.1 on 2026-08-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_book_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='record_date',
            new_name='last_update',
        ),
    ]
