# Generated by Django 6.1 on 2026-08-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_rename_record_date_book_last_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='BookAuthor',
        ),
    ]
